[project]
name = "berlinbnb-pipeline"
version = "0.1.0"
description = "Berlin BnB Data Pipeline with Apache Airflow"
requires-python = ">=3.8"
dependencies = [
    "pyspark",
    "pandas"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
